# Generated by Django 3.0.6 on 2020-05-20 20:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookflixapp', '0004_usuario_usuariocust'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tarjeta',
            field=models.CharField(max_length=16, validators=[django.core.validators.RegexValidator('^(\\d{16})$', 'Debe introducir un numero de 16 digitos')], verbose_name='Tarjeta de credito'),
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookflixapp.Usuario')),
            ],
        ),
    ]
